#!/bin/bash

warn()
{
    if [ -z "$quiet" ] ; then
        (>&2 echo -e "\e[1;38;05;9m$1\e[m")
    fi
}

out()
{
    if [ -z "$quiet" ]; then
        echo "$1"
    fi
}

throw()
{
    warn "$1"
    exit 1
}

if [ "$EUID" -ne 0 ]; then
  sudo "$(readlink -f $0)"
  exit 0
fi

isEnabled=$(php -m | grep xdebug)
distro=$(lsb_release -is)

case "$distro" in
  'Ubuntu')
    phpv=$(php -r '$v = phpversion(); echo "{$v[0]}.{$v[2]}\n";')
    if [ -z "$phpv" ]; then
        throw "Can\'t php is not installed"
    fi
    if [ -z "$isEnabled" ] ; then
      phpenmod -v "$phpv" xdebug
    else
      phpdismod -v "$phpv" xdebug
    fi
    systemctl restart "php${phpv}-fpm.service"
    ;;
  *)
    throw "Unsupported $distro distro"
    ;;
esac
